### ISSUE TITLE
Can't Log out on android devices 

### ISSUE THREAD

**Issue by anupSharma** [ManifestWebDesign/twitter-connect-plugin#17]
i m using plugin twitter-connect-plugin with ionic project 
when call login method it's working perfect but when called logout  just print logout success, But after call login previous login user information are shown.

**Comment by TheBosZ** [comment]
Can you try this method: http://stackoverflow.com/questions/29743676/how-to-logout-from-twitter-using-fabric-sdk-for-android

If I have time later today, I'll see if I can figure out a working solution.

**Comment by TheBosZ** [comment]
Okay, I've figured out what's going on. When you call "Logout" on the plugin, the app destroys the session and logs the user out. When "Login" is called, the Twitter library automatically displays the previous user **regardless** if the user has logged out.

I tested this by checking the session before trying to login. After a logout, the session is null so the app has no idea who has logged in. Unfortunately, the Twitter library automatically remembers.

Unfortunately, this is not something that can be fixed by anyone other than Twitter themselves.
